### PR TITLE
Improve the cookiecutter usage

### PR DESCRIPTION
**Pull request by scoopex**
This PR has dependencies to https://github.com/osism/osism.github.io/pull/310

- improve the layers of the image build to make them more efficent
- added a entry script to prevent the usage of "sudo chown...."
- added a makefile 
   - to install and execute the dependencies in a venv
   - to add a rekeying mechnism, to show the contents of the ansible vault 
- adapted the linkt to the documentation

### CODE REVIEW

**Comment by scoopex** [comment]
Improved, a first highlevel feedback would be nice.

**Comment by berendt** [comment]
I don't like the 2nd requirements file. It all has to go into one file and that's it. The approach of using Makefile to automate things like rekey is fine.

**Comment by berendt** [comment]
> I don't like the 2nd requirements file. It all has to go into one file and that's it. The approach of using Makefile to automate things like rekey is fine.

Also the Makefile has to be part of osism/cfg-generics and not be part of the cfg-cookiecutter repository itself.

**Comment by scoopex** [comment]
Makefile will be added to the osism/cfg-generics with https://github.com/osism/cfg-generics/pull/397

**Comment by scoopex** [comment]
@berendt Ready for review :-)

**Comment by scoopex** [comment]
@berendt : Ready for review

**Pull request merged**
